### Create New User 
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "bbbbfgdfgdgbb@gmail.com",
    "password": "bbbbbbb"
}


### sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "bbbbdfgdgbb@gmail.com",
    "password": "bbbbbbb"
}

### sign out
POST http://localhost:3000/auth/signout

### get signed in user data
GET http://localhost:3000/auth/me
### get user by id

GET http://localhost:3000/auth/2

### get all users with this email

GET  http://localhost:3000/auth

### update user

PATCH http://localhost:3000/auth/6324
content-type: application/json

{
    "email": "new777777@gmail.com",
    "password": "777777"
}

### remove user

DELETE http://localhost:3000/auth/5

# ### test session set
# GET http://localhost:3000/colors/ggg


# ### test session get
# GET http://localhost:3000/colors